### ISSUE TITLE
"Permission denied" error when rendering PDF with Ghostscript >= 9.50

### ISSUE THREAD

**Issue by lightman63** [bmjcode/tkDocViewer#1]
Code : 
pdfview = DocViewer(pdfframe, width=620, height=700)
pdfview.pack()
pdfview.display_file(filename)

On Python 3.8

Execution :

Error: /invalidfileaccess in --file--
Operand stack:
(google.com.pdf) (r)
Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--
Dictionary stack:
   --dict:728/1123(ro)(G)--   --dict:0/20(G)--   --dict:75/200(L)--
Current allocation mode is local
Last OS error: Permission denied

Ghostscript command line (return code = 1)
/usr/bin/gs -q -dNODIPLAY -c 
"(google.com.pdf) (r) file runpdfbegin pdfpagecount = quit"

**Comment by lightman63** [comment]
Nood to add -dNOSAFER in the gs command.
It's a change since 9.50 version of ghostscript.

**Comment by bmjcode** [comment]
Hey there @lightman63! Thanks for reporting this problem, and for tracking down the solution.

I have discontinued development of tkDocViewer, which suffers from significant design limitations, and therefore will not be adding this fix to the code. (I made that decision before seeing your issue report.) However, I've documented this in the README for others who may still be using tkDocViewer.

**Comment by icmimaresat** [comment]
> Nood to add -dNOSAFER in the gs command.
> It's a change since 9.50 version of ghostscript.

How can i add -dNOSAFER in the gs command ? , im getting the same error and i cant find any solution in web please help im gonna be crazy

**Comment by bmjcode** [comment]
Upon further consideration, you all are right and I was wrong. I still think people would be better served with something like Qt and Poppler, but if I leave this unfixed, it's eventually gonna cause enormous headaches for someone, probably me. I've pushed out a new release that fixes this issue. Thanks again @lightman63 for reporting this and identifying the solution.
